/* Replace with your SQL commands */
CREATE TABLE users (Id UUID PRIMARY KEY, email VARCHAR(100) UNIQUE, password VARCHAR(100), nickname VARCHAR(30) UNIQUE)
CREATE TABLE tag (Id SERIAL PRIMARY KEY , creator UUID, name VARCHAR(40) UNIQUE, sortOrder INT DEFAULT 0, FOREIGN KEY (creator) REFERENCES users (Id) ON DELETE CASCADE)
CREATE TABLE userTag (users UUID REFERENCES users(Id) ON DELETE CASCADE, tagId INT REFERENCES tag(Id) ON DELETE CASCADE)
